### ISSUE TITLE
The future of this project

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/juno#1]
## Context
In the last days me and @angelorc have been working on this fork of [Alexander's original Juno ](https://github.com/fissionlabsio/juno). The main differences between this tool and the original one are the following: 

- Support for multiple database drivers (PostgreSQL and MongoDB)
- Easy customizazion thanks to the `RegisterBlockHandler`, `RegisterTxHandler` and `RegisterMsgHandler` methods

Aside from those features, this parser allows to get and store the following data of a Cosmos SDK chain:

- Blocks
- Transactions
- Pre commits
- Validators

## GraphQL
The next idea me and Angelo had was to implement a Go-based GraphQL server so that with a single executable we could have started either the parser (`juno parse`) or the GQL server (`juno start-gql`). 

Unfortunately, we've discovered that this might be a lot more complicated that it sounds like and could cost a lot of time. To overcome this problem, Angelo found some useful tools that might help us auto-generate a GraphQL server.

I've also asked Alexander an opinion and he said that if he would have to do it, he would use a generator (as he did with [GaiaQL](https://gaiaql.fissionlabs.io/)) to avoid having to do the heavy work.

So far, the best tools we have found are the following: 

- [Mongoke](https://mongoke.now.sh/docs/), a tool that generates a custom GraphQL server based on a Mongo database. 
- [Hasura](https://hasura.io/), a tools that connects a PostgreSQL database and generates a GraphQL backend (this is the one used by GaiaQL)

Now, we need to decide what to do next. Our options are the following.

1. Implement a custom Go-based GraphQL server.  
   This might be the best option on the long run as we don't have to rely on third party tools, but it might also require us a lot more work to do as well as to maintain this heavily in the future. 

2. Use a GraphQL generator.  
   This is the option we should take if we want to start playing with GraphQL in the short time, and that will require us less code maintenance and less work. The downside is that we might now have all the features we want.

Personally, I would go with the following strategy: 

1. Use a generator to build the first version of the GraphQL APIs.  
   Particularly I would use Hasura as it has already been shown it works properly.

2. Once we have a nice set of APIs, we can have @MonikaCat start building the new BigDipper on top of them. This would allow us to see if we need to tweak them or not. 

3. If they are all OK, we can think if we should implement them inside the Go binary or not. 

What are your thoughts about it? @kwunyeung @MonikaCat @bragaz 

#### Note
If we decide for the second option and choose Hasura, I'd like to point out what Alexander said to me: 

> You’ll have to tweak the relations a bit

We should further investigate this and see what he meant with it.

**Comment by bragaz** [comment]
I personally think that we should go for the second option because implementing a new Go-based GraphQL server will surely take us quite a lot of time, need constant maintenance and proper testing before we would be able to use that in production not to mention that that “time” could be used for Desmos and the continuos improvement of the whole mid-layer app. At least for the moment. 
We can always implement the first option later when we understand better how the whole system behave with huge amounts of data

**Comment by MonikaCat** [comment]
Good job Riccardo, I agree with you and @bragaz  :) Implementing a new Go-based GraphQL server will take quite a lot of time and it might be hard to maintain it later on (probably the most important factor here). Since we are all relatively new to GraphQL and may be unaware of certain issues that could extend the development time, I personally think that the strategy suggested above by Riccardo makes sense and we should try to follow it.

**Comment by kwunyeung** [comment]
The aim for the parser and the gql server is to serve as a middle layer to have a better UX on the dapps. Don’t reinvent the wheel. We should use existing tool to build a working model as soon as we can. We use the gql generator for now. We can consider building a Go version later if we need more features than the existing gql server in the future.

Great! I’m excited and look forward to the outcome.

**Comment by kwunyeung** [comment]
I have just taken a look at `Mongoke`. I think it's too fresh, I see the author posted it on [Reddit 3 months ago](https://www.reddit.com/r/graphql/comments/dte8g0/instant_graphql_with_mongodb_database/),  for now but the idea is good. It takes a yaml configuration file which setup the schema, authorization and relations of the collections, then just run with docker. There is one thing I don't like on the existing `GaiaQL` which is what the Hausra would bring us from its automation. It exposes fully the schema of tables and views of the database which make the GraphQL schema looks complicated.

My [comment](https://github.com/desmos-labs/desmos/issues/60#issuecomment-591223219) here still valid. Especially I see the ready made aggregation functions in Hasura, subscriptions and the queries are just like using SQL with the `order_by`, `limit`, etc.

@RiccardoM what exactly did Bez's mean for the comment of tweaking the relations? I do think we should go with Hasura for now as it's production ready. So @bragaz please go for it. @MonikaCat can you build something simple with `Mongoke` on the existing structure of Big Dipper MongoDB? I do want to see how it works.

P.S. I'm personally a more NoSQL guy.

**Comment by RiccardoM** [comment]
@kwunyeung I think he meant that the database should be setup accordingly to make sure Hasura works properly. This morning I've fixed a couple of bugs with the parser and tried setting up the PostgreSQL database as well as the GraphQL APIs with Hasura. 

I've managed to get everything working in a couple of hours, and I've now written a [detailed guide](https://github.com/desmos-labs/juno/blob/master/.docs/postgres-graphql-setup.md) so that anyone that wants to try it can do it in a couple of minutes.

The system now looks ready to be used, and it's working flawlessly. I would you @kwunyeung and @MonikaCat to try it out. What you have to do is: 

1. Clone this repo. 
   ```bash
   git clone git@github.com:desmos-labs/juno.git
   ```

2. Build the executable. 
   ```bash
   make install
   ```

3. Follow the PostgreSQL setup guide [here](https://github.com/desmos-labs/juno/blob/master/.docs/postgres-graphql-setup.md) (it tells you what to write inside `config.yml` too). 

4. Start the parser. 
   ```bash
   juno parse config.yml
   ```

5. Enjoy your GraphQL server on [localhost:8080](http://localhost:8080).

**Comment by RiccardoM** [comment]
I'm going to close this issue. The Desmos-related part of the work is being done inside [Djuno's repo](https://github.com/desmos-labs/djuno
